if(DATAMANAGEMENT_BUILD_TESTS OR DATAMANAGEMENT_BUILD_ALL)
    message(STATUS "Generating tests")
    if(DATAMANAGEMENT_CALCULATE_COVERAGE)
        message(STATUS "Calculating Code Coverage")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage")
    endif()
    enable_testing()
    add_subdirectory(tests)
endif()